#!/usr/bin/env bash

# Try to get rid of a lot of stuff generated by all the autotools

clean_dir () { (cd $1 ; rm -f Makefile Makefile.in *.o *.mod *.a datetime_tests ;); }
    
rm -f configure

rm -f datetime-fortran.pc
rm -f *.gz aclocal.m4 depcomp install-sh missing \
   autoscan.log Makefile Makefile.in test-driver
rm -f config.log config.status configure.scan

rm -rf autom4te.cache

#(cd tests ; rm -f Makefile Makefile.in datetime_tests)

clean_dir src/lib
clean_dir src/tests
