#!/usr/bin/env bash

# Try to get rid of a lot of stuff generated by all the autotools

clean_objs () { (cd $1 ; rm -f *.o *.mod *.a ;); }
    
rm -f configure

rm -f datetime-fortran.pc
rm -f *.gz aclocal.m4 depcomp install-sh missing \
   autoscan.log Makefile Makefile.in test-driver
rm -f config.log config.status configure.scan

rm -rf autom4te.cache

(cd tests ; rm -f Makefile Makefile.in datetime_tests)

clean_objs .
clean_objs tests
